name: connect

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  connect:
    name: connect
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH server for Actor
        uses: alexellis/setup-sshd-actor@master
          #- name: Connect to activated SSH gateway
          #uses: alexellis/actuated-ssh-gateway-action@master
          #with:
          #gateway: 139.162.243.207
          #secure: true
      - name: install tmate
        run: |
          sudo apt install tmate -y
          TERM=st-256color tmate
      - name: Setup a blocking tmux session
        uses: alexellis/block-with-tmux-action@master
